# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1385bfe5558a5a83682acb25acd87014e1c41fb889a2bf9470b3f103e3a5a8053e44ec41958de94644c638d57b3c5fdd25735cea84a9cef08de2e93f7e3c715

test:
  secret_key_base: f2933bd8af7e95fa5a5dfcad62b4f5a620b9c9acda76dc04572cc667b1b56d8a8f87d3f3070eada4df6d43d325e9a5cd4554c88305e877a34ffe71fa972734a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
